@startuml Manage appointment (GET ONE)

header Backend project 
footer Page %page% of %lastpage%
title "Manage appointment (GET ONE)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:appointment" as routerAppointmnent
participant "<<middleware>>\nauth" as auth
participant "<<controllers>>\n:appointment" as controllerappointment
participant "<<model>>\n:appointment" as modelappointment
database "<<MongoDB>>\n:appointment" as appointmentDatabase

client->server ++:req.get('/appointment/:id')
server->routerAppointmnent ++:app.use('/appointment',appointment)
routerAppointmnent --> auth ++:protect()
auth -> controllerappointment ++:getAppointment()
controllerappointment->modelappointment ++:findById(req.params.id)
modelappointment ->appointmentDatabase ++: AppointmentSchema
appointmentDatabase --> modelappointment --: appointment
controllerappointment <-- modelappointment --: appointment
controllerappointment->client --:response

@enduml
